language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - 37.139.24.127
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/var/www/brummefar.dk
  - REMOTE_USER=travis
  - REMOTE_HOST=37.139.24.127
script: npm run dist
before_script:
- chmod 600 travis && mv travis ~/.ssh/id_rsa
before_install:
- openssl aes-256-cbc -K $encrypted_420dc9b54b7f_key -iv $encrypted_420dc9b54b7f_iv
  -in travis.enc -out travis -d
after_success:
- "./scripts/deploy.sh"
